### ISSUE TITLE
gradlew missing in the repo

### ISSUE THREAD

**Issue by samuell** [mberacochea/nf-linter#1]
The README refers to the `./gradlew` file, but it is not available in the repo currently.

**Comment by mberacochea** [comment]
Hey, thanks for letting me know.

I'll fix the building instructions!

**Comment by mberacochea** [comment]
I've added the wrapper, https://github.com/mberacochea/nf-linter/commit/97f26669d5866cdd2e3e8c07da8261e9b8f5f458
